##端口号
server:
  port: 8880




dubbo:
    server: true
    application:
      name: dubbo_server
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20882
    scan:
      base-packages: serviceImpl