##端口号
server:
  port: 8881



dubbo:
    application:
      name: dubbo_cli
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
    scan:
      base-packages:  app